inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Exclude:
    - 'app/views/conservation_records/_conservation_record.json.jbuilder'