{{- if .Values.railsMigrateDatabase -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: treatment-database-rds-migration
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: treatment-database-rds-migration
    {{/* REC: This should be the chart name and version: {{ .Chart.Name }}-{{ .Chart.Version \| replace "+" "_" }}.*/}}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{/* REC: This should always be set to {{ .Release.Service }}. It is for finding all things managed by Helm. */}}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{/* REC: This should be the {{ .Release.Name }}. It aids in differentiating between different instances of the same application.*/}}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{/* OPT: The version of the app and can be set to {{ .Chart.AppVersion }}.*/}}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{/* OPT: This is a common label for marking the different roles that pieces may play in an application. For example, app.kubernetes.io/component: frontend. */}}
    app.kubernetes.io/component: rds-migration-job
    {{/* OPT: When multiple charts or pieces of software are used together to make one application. For example, application software and a database to produce a website. This can be set to the top level application being supported*/}}
    app.kubernetes.io/part-of: {{ .Release.Name }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release/
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: treatment-database-rds-migration
      labels:
        app.kubernetes.io/name: treatment-database-rds-migration
        {{/* REC: This should be the chart name and version: {{ .Chart.Name }}-{{ .Chart.Version \| replace "+" "_" }}.*/}}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        {{/* REC: This should always be set to {{ .Release.Service }}. It is for finding all things managed by Helm. */}}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        {{/* REC: This should be the {{ .Release.Name }}. It aids in differentiating between different instances of the same application.*/}}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{/* OPT: The version of the app and can be set to {{ .Chart.AppVersion }}.*/}}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        {{/* OPT: This is a common label for marking the different roles that pieces may play in an application. For example, app.kubernetes.io/component: frontend. */}}
        app.kubernetes.io/component: rds-migration-job
        {{/* OPT: When multiple charts or pieces of software are used together to make one application. For example, application software and a database to produce a website. This can be set to the top level application being supported*/}}
        app.kubernetes.io/part-of: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
      - name: treatment-database-rds-migration
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: RAILS_LOG_TO_STDOUT
          value: 'true'
        - name: RAILS_ENV
          value: production
        - name: TREATMENT_DATABASE_ADAPTER
          value: mysql2
        - name: TREATMENT_DATABASE_HOST
          value: {{ .Values.databaseProperties.dbHost }}
        - name: TREATMENT_DATABASE_NAME
          value: {{ .Values.databaseProperties.dbName }}
        - name: TREATMENT_DATABASE_POOL
          value: "{{ .Values.databaseProperties.dbPool }}"
        - name: TREATMENT_DATABASE_PORT
          value: "{{ .Values.databaseProperties.dbPort }}"
        - name: TREATMENT_DATABASE_TIMEOUT
          value: "{{ .Values.databaseProperties.dbTimeout }}"
        - name: TREATMENT_DATABASE_USERNAME
          value: {{ .Values.databaseProperties.dbUser }}
        - name: TREATMENT_DATABASE_PASSWORD
          value: {{ .Values.databaseProperties.dbPassword }}
        - name: RAILS_MASTER_KEY
          value: {{ .Values.railsMasterKey }}
        command:
        - rails
        - db:migrate
  {{- end -}}
---
{{- if .Values.railsMigrateDatabase -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: treatment-database-rds-rollback
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: treatment-database-rds-rollback
    {{/* REC: This should be the chart name and version: {{ .Chart.Name }}-{{ .Chart.Version \| replace "+" "_" }}.*/}}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{/* REC: This should always be set to {{ .Release.Service }}. It is for finding all things managed by Helm. */}}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{/* REC: This should be the {{ .Release.Name }}. It aids in differentiating between different instances of the same application.*/}}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{/* OPT: The version of the app and can be set to {{ .Chart.AppVersion }}.*/}}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{/* OPT: This is a common label for marking the different roles that pieces may play in an application. For example, app.kubernetes.io/component: frontend. */}}
    app.kubernetes.io/component: rds-migration-job
    {{/* OPT: When multiple charts or pieces of software are used together to make one application. For example, application software and a database to produce a website. This can be set to the top level application being supported*/}}
    app.kubernetes.io/part-of: {{ .Release.Name }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release/
    "helm.sh/hook": pre-rollback
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: treatment-database-rds-rollback
      labels:
        app.kubernetes.io/name: treatment-database-rds-rollback
        {{/* REC: This should be the chart name and version: {{ .Chart.Name }}-{{ .Chart.Version \| replace "+" "_" }}.*/}}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        {{/* REC: This should always be set to {{ .Release.Service }}. It is for finding all things managed by Helm. */}}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        {{/* REC: This should be the {{ .Release.Name }}. It aids in differentiating between different instances of the same application.*/}}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{/* OPT: The version of the app and can be set to {{ .Chart.AppVersion }}.*/}}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        {{/* OPT: This is a common label for marking the different roles that pieces may play in an application. For example, app.kubernetes.io/component: frontend. */}}
        app.kubernetes.io/component: rds-migration-job
        {{/* OPT: When multiple charts or pieces of software are used together to make one application. For example, application software and a database to produce a website. This can be set to the top level application being supported*/}}
        app.kubernetes.io/part-of: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: treatment-database-rds-rollback
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RAILS_LOG_TO_STDOUT
              value: 'true'
            - name: RAILS_ENV
              value: production
            - name: TREATMENT_DATABASE_ADAPTER
              value: mysql2
            - name: TREATMENT_DATABASE_HOST
              value: {{ .Values.databaseProperties.dbHost }}
            - name: TREATMENT_DATABASE_NAME
              value: {{ .Values.databaseProperties.dbName }}
            - name: TREATMENT_DATABASE_POOL
              value: "{{ .Values.databaseProperties.dbPool }}"
            - name: TREATMENT_DATABASE_PORT
              value: "{{ .Values.databaseProperties.dbPort }}"
            - name: TREATMENT_DATABASE_TIMEOUT
              value: "{{ .Values.databaseProperties.dbTimeout }}"
            - name: TREATMENT_DATABASE_USERNAME
              value: {{ .Values.databaseProperties.dbUser }}
            - name: TREATMENT_DATABASE_PASSWORD
              value: {{ .Values.databaseProperties.dbPassword }}
            - name: RAILS_MASTER_KEY
              value: {{ .Values.railsMasterKey }}
          command:
            - rails
            - db:rollback
  {{- end -}}
