apiVersion: v1
kind: Service
metadata:
  name: {{ include "treatment-database.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "treatment-database.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: http
    targetPort: 3000
  selector:
  {{- include "treatment-database.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app