# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: host.docker.internal
  socket: /tmp/mysql.sock

#staging is for hosting app in dev mode in AWS
staging:
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV['MYSQL_HOST'] %>
  username: <%= ENV['MYSQL_USER_NAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  pool: 5
  database: <%= ENV['MYSQL_DB'] %>
#
# development:
#   <<: *default
#   database: db/development.sqlite3

development:
  <<: *default
  database: db/development_mysql

# development:
#   adapter: mysql2
#   database: db/development.mysql
#   username: root
#   password: mysql
#   host: localhost
#   socket: /tmp/mysql.sock

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: db/test_mysql

production:
  <<: *default
  database: db/production_mysql
